# Introduction to pandas
What is pandas?
A powerful library for dta manipulation and analysis in Python.



Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [3]:
print("Introduction to pandas")

Introduction to pandas

In [5]:
!conda install pandas

'conda' is not recognized as an internal or external command,
operable program or batch file.

In [9]:
import pandas as pd
print(pd.__version__)

3.0.3

In [14]:
import pandas as pd

In [32]:
df = pd.read_csv("data/iris.csv")

In [19]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [21]:
df.tail()

     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [24]:
df.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [35]:
df["sepal.length"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal.length, Length: 150, dtype: float64

In [53]:
df2 = pd.read_csv("data/data.csv")
df2.dropna()
df2.fillna(0, inplace=True)
df2.rename(columns={"sepal.length": "SL"})

      SL  sepal.width  petal.length  petal.width    variety
0    5.1          3.5           1.4          0.2     Setosa
1    4.9          3.0           1.4          0.2     Setosa
2    4.7          3.2           0.0          0.2     Setosa
3    4.6          3.1           1.5          0.2     Setosa
4    5.0          3.6           1.4          0.2     Setosa
..   ...          ...           ...          ...        ...
145  6.7          3.0           5.2          2.3  Virginica
146  6.3          2.5           5.0          1.9  Virginica
147  6.5          3.0           5.2          2.0  Virginica
148  6.2          3.4           5.4          2.3  Virginica
149  5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [57]:
df2.info()
df2['sepal.length'] = df2['sepal.length'].astype(int)

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB